/*
 * home-iot-api
 *
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using Calc.Test.Attributes;

using Microsoft.AspNetCore.Authorization;
using Calc.Test.Models;
using Calc.Test.Services;

namespace Calc.Test.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class CALCApiController : ControllerBase
    {
        private readonly IMathService _mathService;

        public CALCApiController(IMathService mathService)
        {
            _mathService = mathService;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>calc value</remarks>
        /// <param name="body"></param>
        /// <param name="operation"></param>
        /// <response code="200">Operation successful.</response>
        /// <response code="400">Invalid request or operation.</response>
        [HttpPost]
        [Route("/s8487458/TEST/1.0.0/Math/calc")]
        [Authorize]
        [ValidateModelState]
        [SwaggerOperation("MathCalcPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(decimal?), description: "Operation successful.")]
        public virtual IActionResult MathCalcPost([FromBody]MathCalcBody body, [FromHeader][Required()]string operation)
        {
            try
            {
                return StatusCode(200, _mathService.Calc(operation, body));
            }
            catch(Exception ex)
            {
                return StatusCode(400, ex.Message);
            }
        }
    }
}
